name: Backup conocimiento.json

on:
  schedule:
    - cron: "*/3 * * * *" # Cada 3 minutos
  workflow_dispatch: # Permite ejecución manual desde GitHub

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar usuario Git
        run: |
          git config user.name "chatbot-ai"
          git config user.email "chatbot@bootcamp.ai"

      - name: Ver contenido actual de conocimiento.json
        run: |
          echo "Contenido actual:"
          cat conocimiento.json || echo "⚠️ Archivo no encontrado"

      - name: Detectar cambios
        run: |
          git add conocimiento.json
          if git diff --cached --quiet; then
            echo "No hay cambios en conocimiento.json. No se hace commit."
            exit 0
          fi

      - name: Hacer commit y push si hubo cambios
        run: |
          git commit -m "🔄 Backup automático de conocimiento.json"
          git push
