name: Backup Chatbot Automático

on:
  schedule:
    - cron: "*/1 * * * *" # cada minuto
  workflow_dispatch: # para ejecutarlo manualmente también

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Hacer commit si hay cambios
        run: |
          if git diff --quiet; then
            echo "Sin cambios, no se hace commit."
          else
            git add conocimiento.json
            git commit -m "Backup automático del chatbot"
            git push
          fi
